"use client";

import { useState } from "react";

import { DirtyForm } from "@/components/ui/dirty-form";
import { Input } from "@/components/ui/input";
import { SubmitButton } from "@/components/ui/submit-button";
import { Textarea } from "@/components/ui/textarea";
import { saveTenantBrandingAction } from "@/lib/domain/premium-operations-actions";

type Branding = { accentColor: string; emailFooter: string; emailFromName: string; logoUrl: string; portalWelcome: string; primaryColor: string; productName: string; pwaEnabled: boolean; status: string };

export function BrandingForm({ initial, tenantName }: { initial: Branding; tenantName: string }) {
  const [primary, setPrimary] = useState(initial.primaryColor);
  const [accent, setAccent] = useState(initial.accentColor);
  const [name, setName] = useState(initial.productName || tenantName);
  return <div className="grid gap-5 xl:grid-cols-[1fr_0.8fr]"><DirtyForm action={saveTenantBrandingAction} className="rounded-2xl border border-border bg-card p-5 shadow-soft"><div className="grid gap-4 sm:grid-cols-2"><Field label="Productnaam"><Input defaultValue={initial.productName} name="productName" onInput={(event) => setName(event.currentTarget.value || tenantName)} /></Field><Field label="Logo URL"><Input defaultValue={initial.logoUrl} name="logoUrl" type="url" /></Field><Field label="Primaire kleur"><div className="flex gap-2"><Input className="w-14 p-1" defaultValue={initial.primaryColor} name="primaryColor" onInput={(event) => setPrimary(event.currentTarget.value)} type="color" /><Input aria-label="Primaire hexkleur" value={primary} onChange={(event) => setPrimary(event.target.value)} /></div></Field><Field label="Accentkleur"><div className="flex gap-2"><Input className="w-14 p-1" defaultValue={initial.accentColor} name="accentColor" onInput={(event) => setAccent(event.currentTarget.value)} type="color" /><Input aria-label="Accent hexkleur" value={accent} onChange={(event) => setAccent(event.target.value)} /></div></Field><Field label="E-mail afzendernaam"><Input defaultValue={initial.emailFromName} name="emailFromName" /></Field><Field label="Welkomsttekst portaal"><Input defaultValue={initial.portalWelcome} name="portalWelcome" /></Field><Field className="sm:col-span-2" label="E-mail footer"><Textarea defaultValue={initial.emailFooter} name="emailFooter" /></Field></div><div className="flex flex-wrap gap-3"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-border px-3 text-sm font-semibold"><input defaultChecked={initial.pwaEnabled} name="pwaEnabled" type="checkbox" />Branded PWA aan</label><label className="flex min-h-11 items-center gap-2 rounded-xl border border-border px-3 text-sm font-semibold"><input defaultChecked={initial.status === "active"} name="active" type="checkbox" />Branding actief</label></div><SubmitButton>Branding opslaan</SubmitButton></DirtyForm><aside className="overflow-hidden rounded-3xl border border-border bg-card shadow-card"><div className="p-5 text-white" style={{ background: `linear-gradient(135deg, ${primary}, ${accent})` }}><p className="text-xs font-semibold uppercase tracking-widest opacity-75">Live preview</p><h2 className="mt-8 text-3xl font-bold">{name}</h2><p className="mt-2 max-w-sm text-sm opacity-85">{initial.portalWelcome || "Welkom in jouw persoonlijke familieportaal."}</p><button className="mt-6 rounded-xl bg-white px-4 py-2 text-sm font-bold" style={{ color: primary }} type="button">Volgende les bekijken</button></div><div className="p-5"><p className="text-sm font-bold text-foreground">Veilige white-label grenzen</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Kleuren en content zijn tenant-scoped. Custom CSS blijft bewust buiten de beheer-UI om stijl- en securitydrift te voorkomen.</p></div></aside></div>;
}
function Field({ children, className = "", label }: { children: React.ReactNode; className?: string; label: string }) { return <label className={`grid gap-2 text-sm font-semibold text-foreground ${className}`}><span>{label}</span>{children}</label>; }
