"use client";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { GrowthAnalyticsReport } from "@/lib/analytics/growth-cohorts";
import { Button } from "@/components/ui/button";
import { StatusPill } from "@/components/shell/ui";

export function GrowthAnalyticsWorkspace({ report }: { report: GrowthAnalyticsReport }) {
  const [dimension, setDimension] = useState<"campaign" | "location" | "program">("campaign");
  const rows = dimension === "campaign" ? report.byCampaign : dimension === "location" ? report.byLocation : report.byProgram;
  return <div className="grid gap-5">
    <section className="rounded-2xl border border-border bg-card p-5 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Cohorttrend</p><h2 className="mt-1 text-lg font-bold">Instroom → plaatsing per maand</h2></div><StatusPill tone="info">testdata uitgesloten</StatusPill></div><div className="mt-5 h-72" aria-label="Cohortconversie per maand"><ResponsiveContainer height="100%" width="100%"><LineChart data={report.cohorts}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" tick={{ fontSize: 12 }} /><YAxis domain={[0, 100]} tick={{ fontSize: 12 }} unit="%" /><Tooltip /><Line dataKey="conversion" name="Plaatsingsconversie" stroke="#0891b2" strokeWidth={3} type="monotone" /></LineChart></ResponsiveContainer></div></section>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Conversiedimensies</p><h2 className="mt-1 text-lg font-bold">Waar groeit de zwemschool?</h2></div><div className="flex gap-1 rounded-xl border border-border bg-muted/30 p-1">{(["campaign", "program", "location"] as const).map((key) => <Button key={key} onClick={() => setDimension(key)} size="sm" variant={dimension === key ? "default" : "ghost"}>{key === "campaign" ? "Campagne" : key === "program" ? "Programma" : "Locatie"}</Button>)}</div></div><div className="mt-5 h-80"><ResponsiveContainer height="100%" width="100%"><BarChart data={rows.slice(0, 10)} layout="vertical" margin={{ left: 24 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" /><YAxis dataKey="label" type="category" width={130} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="intakes" fill="#cbd5e1" name="Intakes" radius={[0, 6, 6, 0]} /><Bar dataKey="placements" fill="#0891b2" name="Plaatsingen" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase tracking-wider text-muted-foreground"><th className="py-3">Segment</th><th>Intakes</th><th>Plaatsingen</th><th>Conversie</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b border-border/60" key={row.key}><td className="py-3 font-semibold">{row.label}</td><td>{row.intakes}</td><td>{row.placements}</td><td><StatusPill tone={row.conversion >= 50 ? "success" : row.conversion >= 25 ? "warning" : "neutral"}>{row.conversion}%</StatusPill></td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-border bg-muted/20 p-4"><h2 className="font-bold">Bronbewijs en interpretatie</h2><ul className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2">{report.evidence.map((item) => <li className="rounded-lg border border-border bg-card px-3 py-2" key={item}>{item}</li>)}</ul></section>
  </div>;
}
