import { expect, test } from "@playwright/test";
import path from "node:path";
import { readFileSync } from "node:fs";
import { readThemeArchive, writeThemeArchive } from "../../lib/theme/theme-package-archive";

test("platform import, draft editing, preview and immutable publication persist across browser sessions", async ({ page, browser }, testInfo) => {
  test.skip(!process.env.THEME_LIBRARY_TEST_EMAIL || !process.env.THEME_LIBRARY_TEST_PASSWORD, "Requires an explicitly seeded isolated local database and platform manager");
  test.setTimeout(180_000);
  const version = `88.0.${Math.floor(Date.now() / 1000)}`;
  await page.goto("/login?next=%2Fplatform%2Fthemes");
  await page.getByLabel("E-mail", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_EMAIL!);
  await page.getByLabel("Wachtwoord", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_PASSWORD!);
  await page.getByRole("button", { name: "Inloggen", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Themabibliotheek", exact: true })).toBeVisible({ timeout: 45_000 });
  await page.getByRole("link", { name: "Pakket importeren", exact: true }).click();
  await page.getByLabel("Nieuwe releaseversie (optioneel)").fill(version);
  await page.getByLabel("Themapakket kiezen").setInputFiles(path.resolve(process.cwd(), "../../tests/fixtures/portal-v42/NXTTRACK-De-Parelroute-Wereld-1-Referentiepakket-1.0.0.zip"));
  await expect(page.getByRole("button", { name: "Bewaar als concept" })).toBeVisible({ timeout: 45_000 });
  await expect(page).toHaveURL(/\/platform\/themes\/import\?import=/);
  await page.reload();
  await page.getByRole("button", { name: "Preview bekijken vóór conceptopslag" }).click();
  const importFrame = page.frameLocator('iframe[title="Importpreview met fictieve gegevens"]');
  await expect(importFrame.locator("[data-rich-journey]")).toBeVisible();
  const previewAsset = importFrame.locator("[data-rich-layer]").first();
  await expect.poll(() => previewAsset.evaluate((element) => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  const previewSource = new URL((await previewAsset.getAttribute("src"))!, page.url());
  const anonymous = await browser.newContext();
  expect((await anonymous.request.get(previewSource.href)).status()).toBe(401);
  previewSource.search = ""; expect((await anonymous.request.get(previewSource.href)).status()).toBe(404);
  await anonymous.close();
  const previewUrl = await page.locator('iframe[title="Importpreview met fictieve gegevens"]').getAttribute("src");
  const previewHeaders = (await page.request.get(previewUrl!)).headers();
  expect(previewHeaders["content-security-policy"]).toContain("frame-ancestors 'self'");
  expect(previewHeaders["content-security-policy"]).toContain("form-action 'none'");
  expect((await page.request.get("/platform/themes")).headers()["content-security-policy"]).toContain("frame-ancestors 'none'");
  await page.getByRole("button", { name: "Bewaar als concept" }).click();
  await expect(page.getByText(`Versie ${version} · revisie 1 · Concept`, { exact: true })).toBeVisible({ timeout: 30_000 });
  const editorUrl = page.url();
  await page.getByRole("button", { name: "Werelden en assets", exact: true }).click();
  await page.getByLabel("Wereldnaam", { exact: true }).fill("");
  await page.getByLabel("Wereldnaam", { exact: true }).fill("Fictieve reviewwereld");
  const anchor = page.getByRole("button", { name: /Layoutanker 1:/ });
  await anchor.focus(); const original = await anchor.getAttribute("aria-label");
  await page.keyboard.press("ArrowRight");
  await expect(anchor).not.toHaveAttribute("aria-label", original!);
  await page.getByRole("button", { name: "Concept opslaan", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 2 · Concept`, { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Portaalpreview", exact: true }).click();
  const frame = page.frameLocator('iframe[title="Interactieve portaalpreview met uitsluitend fictieve gegevens"]');
  await expect(frame.locator("[data-rich-journey]")).toBeVisible();
  await expect(frame.locator("[data-rich-journey]").getByText("Fictieve reviewwereld", { exact: true })).toBeVisible();
  const images = frame.locator("[data-rich-layer]"); await expect(images).toHaveCount(3);
  await expect.poll(async () => images.evaluateAll((elements) => elements.every((element) => (element as HTMLImageElement).complete && (element as HTMLImageElement).naturalWidth > 0))).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("theme-draft-preview.png"), fullPage: true });
  await page.getByRole("button", { name: "Controle en publicatie", exact: true }).click();
  for (const name of ["Landscape, lagen", "Portrait, gids", "Geen curriculumregels", "Aandachtspunten gelezen"]) await page.getByLabel(new RegExp(name)).check();
  await page.getByRole("button", { name: "Review vastleggen", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 2 · Review vastgelegd`, { exact: true })).toBeVisible();
  // A later edit must invalidate review before any publication request can proceed.
  await page.getByRole("button", { name: "Werelden en assets", exact: true }).click();
  await page.getByLabel("Wereldnaam", { exact: true }).fill("Fictieve reviewwereld bijgewerkt");
  await page.getByRole("button", { name: "Concept opslaan", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 3 · Concept`, { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Controle en publicatie", exact: true }).click();
  await expect(page.getByRole("button", { name: "Versie publiceren", exact: true })).toBeDisabled();
  for (const name of ["Landscape, lagen", "Portrait, gids", "Geen curriculumregels", "Aandachtspunten gelezen"]) await page.getByLabel(new RegExp(name)).check();
  await page.getByRole("button", { name: "Review vastleggen", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 3 · Review vastgelegd`, { exact: true })).toBeVisible();
  await page.getByLabel(/Publiceer deze gecontroleerde versie/).check();
  await page.getByRole("button", { name: "Versie publiceren", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 3 · Gepubliceerd`, { exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent("download"); await page.getByRole("link", { name: "Exporteer presentatie", exact: true }).click();
  const download = await downloadPromise; await download.saveAs(testInfo.outputPath("published-presentation.zip"));
  // Reload from a new browser context; the library is database-backed, not tab memory.
  const fresh = await browser.newContext({ storageState: await page.context().storageState() });
  const reopened = await fresh.newPage(); await reopened.goto(editorUrl);
  await expect(reopened.getByText(`Versie ${version} · revisie 3 · Gepubliceerd`, { exact: true })).toBeVisible();
  await reopened.getByRole("button", { name: "Werelden en assets", exact: true }).click();
  await expect(reopened.getByLabel("Wereldnaam", { exact: true })).toHaveValue("Fictieve reviewwereld bijgewerkt");
  await expect(reopened.getByLabel("Wereldnaam", { exact: true })).toBeDisabled();
  await fresh.close();
});

test("a manifestless image archive requires explicit mapping and resumes its saved preview after reload", async ({ page }) => {
  test.skip(!process.env.THEME_LIBRARY_TEST_EMAIL || !process.env.THEME_LIBRARY_TEST_PASSWORD, "Requires an explicitly seeded isolated local database and platform manager");
  test.setTimeout(150_000);
  const original = readThemeArchive(readFileSync(path.resolve(process.cwd(), "../../tests/fixtures/portal-v42/NXTTRACK-De-Parelroute-Wereld-1-Referentiepakket-1.0.0.zip")));
  const source = JSON.parse(original.get("theme.json")!.toString()), assets = JSON.parse(original.get("assets.json")!.toString()), world = source.worlds[source.defaultWorld];
  const bytes = writeThemeArchive(new Map([...original].filter(([name]) => /\.(png|webp|jpg|avif)$/.test(name))));
  await page.goto("/login?next=%2Fplatform%2Fthemes%2Fimport");
  await page.getByLabel("E-mail", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_EMAIL!); await page.getByLabel("Wachtwoord", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_PASSWORD!);
  await page.getByRole("button", { name: "Inloggen", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Importeer een nieuwe zwemwereld" })).toBeVisible({ timeout: 45_000 });
  await page.getByLabel("Themapakket kiezen").setInputFiles({ name: "loose-images.zip", mimeType: "application/zip", buffer: bytes });
  await expect(page.getByRole("heading", { name: "Geef de losse beelden hun plek" })).toBeVisible({ timeout: 45_000 });
  await expect(page).toHaveURL(/\?import=/); await page.reload();
  await page.getByLabel("Naam", { exact: true }).fill("Fictieve begeleide wereld");
  await page.getByLabel("Thema-ID", { exact: true }).fill(`guided-browser-${Date.now()}`);
  await expect(page.getByRole("button", { name: "Koppeling analyseren en preview openen" })).toBeDisabled();
  for (const orientation of ["landscape", "portrait"] as const) {
    await page.getByRole("button", { name: orientation === "landscape" ? "Liggend" : "Staand", exact: true }).click();
    await page.getByLabel("Achtergrond").selectOption(assets[world.scenes[orientation].layers.back].path);
    await expect.poll(() => page.getByAltText(/compositie$/).evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
    await page.getByRole("button", { name: "Routepunt invoeren" }).click(); await page.getByRole("button", { name: "Routepunt invoeren" }).click();
    await page.getByLabel("X %", { exact: true }).first().fill("15"); await page.getByLabel("X %", { exact: true }).last().fill("85");
  }
  await page.getByRole("button", { name: "Koppeling analyseren en preview openen" }).click();
  await expect(page.getByRole("heading", { name: "Fictieve begeleide wereld", exact: true })).toBeVisible({ timeout: 45_000 });
  await page.reload(); await page.getByRole("button", { name: "Preview bekijken vóór conceptopslag" }).click();
  const frame = page.frameLocator('iframe[title="Importpreview met fictieve gegevens"]');
  await expect(frame.locator("[data-rich-journey]")).toBeVisible();
  await expect.poll(() => frame.locator("[data-rich-layer]").first().evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await page.getByRole("button", { name: "Bewaar als concept" }).click();
  await expect(page.getByText("Versie 1.0.0 · revisie 1 · Concept", { exact: true })).toBeVisible();
});

test("platform world binding is explicit, replaces an optimistic revision and rolls back the full presentation", async ({ page }) => {
  test.skip(!process.env.THEME_LIBRARY_TEST_EMAIL || !process.env.THEME_LIBRARY_TEST_PASSWORD, "Requires the local publication and curriculum integration fixtures");
  test.setTimeout(120_000);
  await page.goto("/login?next=%2Fplatform%2Fthemes%2Fbindings");
  await page.getByLabel("E-mail", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_EMAIL!); await page.getByLabel("Wachtwoord", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_PASSWORD!);
  await page.getByRole("button", { name: "Inloggen", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Wereldkoppelingen", exact: true })).toBeVisible({ timeout: 45_000 });
  const tenantId = process.env.THEME_LIBRARY_TEST_TENANT ?? await page.locator('select[name="tenant"] option').filter({ hasText: /^Fictional visual tenant$/ }).first().getAttribute("value");
  expect(tenantId).toBeTruthy(); await page.locator('select[name="tenant"]').selectOption(tenantId!); await page.getByRole("button", { name: "Openen", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`tenant=${tenantId}`));
  const mode = page.locator("section").filter({ has: page.getByRole("heading", { name: "Themakeuze beheren", exact: true }) });
  await expect(mode).toBeVisible();
  if (await mode.getByRole("button", { name: "Platformbeheer inschakelen", exact: true }).count()) {
    await mode.getByLabel("Reden", { exact: true }).fill("Fictieve browsertest expliciet platformbeheer"); await mode.getByRole("button", { name: "Platformbeheer inschakelen", exact: true }).click();
    await expect(mode.getByRole("button", { name: "Bestaande themakeuze herstellen", exact: true })).toBeVisible();
  }
  const section = page.locator("section").filter({ has: page.getByRole("heading", { name: "Curriculumwereld koppelen", exact: true }) });
  await section.locator('select[name="target"]').selectOption({ index: 1 });
  const selectedTarget = await section.locator('select[name="target"]').inputValue();
  const worldOptions = await section.locator('select[name="world"] option').evaluateAll((options) => options.map((option) => (option as HTMLOptionElement).value).filter(Boolean));
  expect(worldOptions.length).toBeGreaterThan(1);
  await section.locator('select[name="world"]').selectOption(worldOptions[0]);
  await section.getByLabel("Reden", { exact: true }).fill("Eerste expliciete wereldkoppeling");
  await section.getByRole("button", { name: /Wereld koppelen|Wereldkoppeling vervangen/ }).click();
  await expect(section.getByText(/Opgeslagen. De nieuwe koppeling/)).toBeVisible();
  await expect(section.locator('select[name="target"]')).toHaveValue(selectedTarget);
  const firstBinding = await section.locator('input[name="expectedBinding"]').inputValue(); expect(firstBinding).toMatch(/^[a-f\d-]{36}$/);
  await section.locator('select[name="world"]').selectOption(worldOptions.at(-1)!);
  await section.getByLabel("Reden", { exact: true }).fill("Tweede expliciete wereldkoppeling");
  await section.getByRole("button", { name: "Wereldkoppeling vervangen", exact: true }).click();
  await expect(section.locator('input[name="expectedBinding"]')).not.toHaveValue(firstBinding);
  const secondBinding = await section.locator('input[name="expectedBinding"]').inputValue();
  const active = page.locator("form").filter({ has: page.locator(`input[name="bindingId"][value="${secondBinding}"]`) });
  await active.getByLabel("Reden", { exact: true }).fill("Herstel de eerste wereld en versie");
  await active.getByRole("button", { name: "Vorige wereld en versie herstellen" }).click();
  await expect(section.locator('input[name="expectedBinding"]')).not.toHaveValue(secondBinding);
  await expect(section.locator('select[name="world"]')).toHaveValue(worldOptions[0]);
  await page.reload(); await section.locator('select[name="target"]').selectOption({ index: 1 });
  await expect(section.locator('select[name="world"]')).toHaveValue(worldOptions[0]);
});

test("a published version forks into a new editable concept, validates assets and restores an earlier revision without rewriting history", async ({ page, browser }) => {
  test.skip(!process.env.THEME_LIBRARY_TEST_EMAIL || !process.env.THEME_LIBRARY_TEST_PASSWORD, "Requires local published-theme fixtures");
  test.setTimeout(180_000);
  await page.goto("/login?next=%2Fplatform%2Fthemes");
  await page.getByLabel("E-mail", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_EMAIL!); await page.getByLabel("Wachtwoord", { exact: true }).fill(process.env.THEME_LIBRARY_TEST_PASSWORD!);
  await page.getByRole("button", { name: "Inloggen", exact: true }).click();
  const library = page.locator("section").filter({ has: page.getByRole("heading", { name: "Geïmporteerde presentaties", exact: true }) });
  await expect(library).toBeVisible({ timeout: 45_000 }); await library.getByLabel("Status").selectOption("published");
  await library.getByRole("link", { name: "Bekijk", exact: true }).first().click();
  await expect(page).toHaveURL(/\/platform\/themes\/[^/]+\/\d+\.\d+\.\d+$/);
  await expect(page.getByText(/· Gepubliceerd$/).first()).toBeVisible();
  const sourceUrl = page.url(), parts = new URL(sourceUrl).pathname.split("/").slice(-2);
  const immutableUpload = await page.request.post(`/api/platform/themes/${parts[0]}/${parts[1]}/assets`, { headers: { Origin: new URL(sourceUrl).origin, "x-theme-filename": "invalid.png" }, data: Buffer.from("not an image") });
  expect(immutableUpload.status()).toBe(409);
  await page.getByRole("button", { name: "Versies", exact: true }).click();
  const version = `100.0.${Math.floor(Date.now() / 1000)}`;
  await page.getByLabel("Nieuw versienummer").fill(version); await page.getByRole("button", { name: "Nieuwe conceptversie maken", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 1 · Concept`, { exact: true })).toBeVisible({ timeout: 45_000 });
  const draftUrl = page.url();
  await page.getByRole("button", { name: "Werelden en assets", exact: true }).click();
  await page.getByLabel("Asset-ID", { exact: true }).fill("verified.upload");
  await page.getByLabel("Afbeelding", { exact: true }).setInputFiles({ name: "fake.png", mimeType: "image/png", buffer: Buffer.from("<svg><script>not-raster</script></svg>") });
  await page.getByRole("button", { name: "Afbeelding controleren", exact: true }).click();
  await expect(page.locator('[role="alert"]').filter({ hasText: /unsupported|Unsupported|Input buffer/ })).toBeVisible();
  await expect(page.getByText(`Versie ${version} · revisie 1 · Concept`, { exact: true })).toBeVisible();
  const files = readThemeArchive(readFileSync(path.resolve(process.cwd(), "../../tests/fixtures/portal-v42/NXTTRACK-De-Parelroute-Wereld-1-Referentiepakket-1.0.0.zip")));
  const image = [...files].find(([name]) => /\.webp$/.test(name))!;
  await page.getByLabel("Afbeelding", { exact: true }).setInputFiles({ name: "verified.webp", mimeType: "image/webp", buffer: image[1] });
  await page.getByRole("button", { name: "Afbeelding controleren", exact: true }).click();
  await expect(page.locator("strong").filter({ hasText: /^verified\.upload$/ })).toBeVisible();
  await page.getByLabel("Type gids").selectOption("none"); await page.getByRole("button", { name: "Gidsinstellingen toepassen" }).click();
  await page.getByLabel("Nieuwe wereld-ID").fill("copied-world"); await page.getByRole("button", { name: "Wereld dupliceren", exact: true }).click();
  await page.getByLabel("Nieuwe beeldkoppeling", { exact: true }).fill("moment.verified");
  await page.getByRole("combobox", { name: "Afbeelding voor beeldkoppeling", exact: true }).selectOption("verified.upload");
  await page.getByRole("button", { name: "Beeldkoppeling toevoegen", exact: true }).click();
  await page.getByLabel("Nieuwe vondst-ID", { exact: true }).fill("verified-shell");
  await page.getByLabel("Titel van nieuwe vondst", { exact: true }).fill("Fictieve testvondst");
  await page.getByRole("combobox", { name: "Afbeelding van nieuwe vondst", exact: true }).selectOption("verified.upload");
  await page.getByRole("button", { name: "Vondst aan concept toevoegen", exact: true }).click();
  await page.getByRole("button", { name: "Overzicht", exact: true }).click();
  await page.getByRole("textbox", { name: "Primaire kleur", exact: true }).fill("#226677");
  await page.getByRole("button", { name: "Concept opslaan", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 2 · Concept`, { exact: true })).toBeVisible();
  await page.reload(); await page.getByRole("button", { name: "Werelden en assets", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "moment.verified", exact: true })).toHaveValue("verified.upload");
  await expect(page.getByLabel("Titel van verified-shell", { exact: true })).toHaveValue("Fictieve testvondst");
  const tile = page.locator("div.rounded-xl.border.p-2").filter({ has: page.locator("strong").filter({ hasText: /^verified\.upload$/ }) });
  await expect.poll(() => tile.locator("img").evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await expect(page.getByLabel("Type gids")).toHaveValue("none");
  await page.getByRole("button", { name: "Controle en publicatie", exact: true }).click();
  for (const name of ["Landscape, lagen", "Portrait, gids", "Geen curriculumregels", "Aandachtspunten gelezen"]) await page.getByLabel(new RegExp(name)).check();
  await page.getByRole("button", { name: "Review vastleggen", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 2 · Review vastgelegd`, { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Versies", exact: true }).click();
  const oldRevision = page.locator("details").filter({ has: page.locator("summary").filter({ hasText: /^Revisie 1 ·/ }) });
  await oldRevision.locator("summary").click(); await expect(oldRevision.getByText(/Assets · verified.upload: toegevoegd/)).toBeVisible();
  await oldRevision.getByLabel("Herstel deze inhoud als nieuwe conceptrevisie").check(); await oldRevision.getByRole("button", { name: "Revisie 1 herstellen", exact: true }).click();
  await expect(page.getByText(`Versie ${version} · revisie 3 · Concept`, { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Werelden en assets", exact: true }).click(); await expect(page.locator("strong").filter({ hasText: /^verified\.upload$/ })).toHaveCount(0);
  const fresh = await browser.newContext({ storageState: await page.context().storageState() }); const reopened = await fresh.newPage();
  await reopened.goto(draftUrl); await expect(reopened.getByText(`Versie ${version} · revisie 3 · Concept`, { exact: true })).toBeVisible();
  await reopened.goto(sourceUrl); await expect(reopened.getByText(/· Gepubliceerd$/, { exact: false }).first()).toBeVisible(); await fresh.close();
});
